/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import modelo.EstadoMaquina;
import modelo.Maquina;

/**
 *
 * @author nataliasabogalrada
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private JButton[][] buttons;
    private ControladorPrincipal controller;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = new ControladorPrincipal();
        buttons = new JButton[3][4];
        dibujarBotones();
        pintarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventana Principal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 1, 24))); // NOI18N

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 223, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    private void dibujarBotones() {
        int ancho = 65;
        int alto = 65;
        int extraX = 40;
        int extraY = 40;
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                //setbounds (posX, posY, ancho, alto)
                if (!(i == 1 && (j == 1 || j == 2))) {
                    extraX = j > 2 ? 100 : 40;
                    buttons[i][j] = new JButton();
                    buttons[i][j].setBounds(
                            ancho * j + extraX,
                            alto * i + extraY,
                            ancho, alto);

                    buttons[i][j].addActionListener(this);
                    panel.add(buttons[i][j]);
                }

            }
        }
    }

    private void pintarBotones() {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                Maquina maquina = controller.entregarMaquina(i, j);

                if (buttons[i][j] != null) {
                    if (controller.estaFueraDeServicio(i, j)) {
                        buttons[i][j].setBackground(Color.RED);

                    } else if (controller.estaRegistrada(i, j)) {
                        buttons[i][j].setBackground(Color.GREEN);
                        Maquina m = controller.entregarMaquina(i, j);
                        buttons[i][j].setText(m.getTipoDeJuego());

                    } else if (controller.isDisponible(i, j)) {
                        buttons[i][j].setBackground(Color.WHITE);
                    }
                }

            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e
    ) {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                if (e.getSource().equals(buttons[i][j])) {
                    int fila = i;
                    int columna = j;
                    if (controller.isDisponible(fila, columna)) {
                        VentanaRegistroMaquina register = new VentanaRegistroMaquina(fila, columna);
                        register.setVisible(true);
                        register.setLocationRelativeTo(null);
                        this.dispose();
                    } else if (controller.estaFueraDeServicio(fila, columna)) {

                        VentanaMotivoFueraServicio fs = new VentanaMotivoFueraServicio();
                        fs.setVisible(true);
                        fs.setLocationRelativeTo(null);
                        this.dispose();

                    } else {
                        VentanaDisponibilidadMaquina disponibilidad = new VentanaDisponibilidadMaquina(fila, columna);
                        disponibilidad.setVisible(true);
                        disponibilidad.setLocationRelativeTo(null);
                        this.dispose();

                    }

                }
            }
        }
    }
}
