/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ControladorPrincipal;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Maquina;

/**
 *
 * @author nataliasabogalrada
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    private JButton[][] buttons;
    private ControladorPrincipal controller;
    private boolean isAdmin;
    private Cliente cliente;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(boolean isAdmin, Cliente cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.controller = new ControladorPrincipal();
        this.isAdmin = isAdmin;
        this.cliente = cliente;
        buttons = new JButton[3][4];
        dibujarBotones();
        pintarBotones();
        mostrarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        panelBotonesXY = new javax.swing.JPanel();
        btnCommandX = new javax.swing.JButton();
        btnCommandY = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventana Principal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Shree Devanagari 714", 1, 24))); // NOI18N

        btnAtras.setText("⤺");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 377, Short.MAX_VALUE)
                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBotonesXY.setBorder(new javax.swing.border.MatteBorder(null));

        btnCommandX.setText("Command X");

        btnCommandY.setText("Command Y");

        javax.swing.GroupLayout panelBotonesXYLayout = new javax.swing.GroupLayout(panelBotonesXY);
        panelBotonesXY.setLayout(panelBotonesXYLayout);
        panelBotonesXYLayout.setHorizontalGroup(
            panelBotonesXYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesXYLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesXYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCommandX, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(btnCommandY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBotonesXYLayout.setVerticalGroup(
            panelBotonesXYLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesXYLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnCommandX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(btnCommandY)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 190, Short.MAX_VALUE)
                        .addComponent(panelBotonesXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        if (isAdmin) {
            VentanaPrincipalAdmin admin = new VentanaPrincipalAdmin();
            admin.setVisible(true);
            admin.setLocationRelativeTo(null);
            this.dispose();
        } else {
            VentanaLogin login = new VentanaLogin();
            login.setVisible(true);
            login.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_btnAtrasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCommandX;
    private javax.swing.JButton btnCommandY;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelBotonesXY;
    // End of variables declaration//GEN-END:variables

    private void dibujarBotones() {
        int ancho = 65;
        int alto = 65;
        int extraX = 40;
        int extraY = 40;
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                //setbounds (posX, posY, ancho, alto)
                if (!(i == 1 && (j == 1 || j == 2))) {
                    extraX = j > 2 ? 100 : 40;
                    buttons[i][j] = new JButton();
                    buttons[i][j].setBounds(
                            ancho * j + extraX,
                            alto * i + extraY,
                            ancho, alto);

                    buttons[i][j].addActionListener(this);
                    panel.add(buttons[i][j]);
                }

            }
        }
    }

    private void pintarBotones() {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                Maquina maquina = controller.entregarMaquina(i, j);

                if (buttons[i][j] != null) {
                    if (controller.estaFueraDeServicio(i, j)) {
                        buttons[i][j].setBackground(Color.RED);

                    } else if (controller.estaRegistrada(i, j)) {
                        buttons[i][j].setBackground(Color.GREEN);
                        Maquina m = controller.entregarMaquina(i, j);
                        buttons[i][j].setText(m.getTipoDeJuego());

                    } else if (controller.isDisponible(i, j)) {
                        buttons[i][j].setBackground(Color.WHITE);
                    }
                }

            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e
    ) {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                if (e.getSource().equals(buttons[i][j])) {
                    int fila = i;
                    int columna = j;
                    if (isAdmin) {
                        if (controller.isDisponible(fila, columna)) {

                            VentanaRegistroMaquina register = new VentanaRegistroMaquina(fila, columna);
                            register.setVisible(true);
                            register.setLocationRelativeTo(null);
                            this.dispose();
                        } else if (controller.estaFueraDeServicio(fila, columna)) {

                            VentanaMotivoFueraServicio fs = new VentanaMotivoFueraServicio(fila, columna, true, null);
                            fs.setVisible(true);
                            fs.setLocationRelativeTo(null);
                            this.dispose();

                        } else {
                            VentanaRegistroMaquina register = new VentanaRegistroMaquina(fila, columna);
                            register.setVisible(true);
                            register.setLocationRelativeTo(null);
                            this.dispose();

                        }
                    } else {

                        if (controller.isDisponible(fila, columna)) {

                            JOptionPane.showMessageDialog(null, "Esta maquina no esta disponible");

                        } else if (controller.estaFueraDeServicio(fila, columna)) {
                            VentanaMotivoFueraServicio motivo = new VentanaMotivoFueraServicio(fila, columna, false, cliente);
                            motivo.setVisible(true);
                            motivo.setLocationRelativeTo(null);
                            this.dispose();

                        } else {
                            VentanaVerMaquinaCliente maquina = new VentanaVerMaquinaCliente(fila, columna, cliente);
                            maquina.setVisible(true);
                            maquina.setLocationRelativeTo(null);
                            this.dispose();

                        }
                    }

                }
            }
        }
    }

    public void mostrarBotones() {
        if (isAdmin) {
            btnCommandX.setVisible(true);
            btnCommandY.setVisible(true);
        } else {
            btnCommandX.setVisible(false);
            btnCommandY.setVisible(false);
        }
    }
}
